version: 2

sources:
  - name: RAW
    description: This is a replica of the Postgres database used by our app
    database: AIRBNB
    schema: RAW
    tables:
      - name: RAW_HOSTS
        description: One record per customer.
      - name: RAW_LISTINGS
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: room_type
            tests:
            - dbt_expectations.expect_column_distinct_count_to_equal:
                value: 4
      - name: RAW_REVIEWS
        description: this contain the reviws from the clients.
